export const WEBSOCKET_RESUMECLEARINGHISTORY = 'WEBSOCKET:RESUMECLEARINGHISTORY';
export const WEBSOCKET_PAUSECLEARINGHISTORY = 'WEBSOCKET:PAUSECLEARINGHISTORY';
export const WEBSOCKET_CLEARHISTORY = 'WEBSOCKET:CLEARHISTORY';
