// Custom actions types
export const WEBSOCKET_RESUMECLEARINGHISTORY = 'WEBSOCKET:RESUMECLEARINGHISTORY';
export const WEBSOCKET_PAUSECLEARINGHISTORY = 'WEBSOCKET:PAUSECLEARINGHISTORY';
export const WEBSOCKET_CLEARHISTORY = 'WEBSOCKET:CLEARHISTORY';
export const WEBSOCKET_LASTONE = 'WEBSOCKET:LASTONE';
export const WEBSOCKET_ACCUMULATION = 'WEBSOCKET:ACCUMULATION';
